var docs = {
  'grid-area': {
    'en': '<p>Specifies a grid item\'s position and size within the grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'lv': '<p>Norāda "grid" elementa/u pozīciju un izmēru tavā "grid".</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'ro': '<p>Specifică poziția și mărimea unui element al gridului în grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'fr': '<p>Définit la position et la taille d\'un élément dans la grille.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'de': '<p>Bestimmt die Position und Grösse eines Elements im Raster.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'nl': '<p>Bepaalt de positie en grootte van een item in het grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'pt-br': '<p>Especifica a posição e o tamanho do item dentro da grade.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'zh-cn': '<p>在网格中指定每一个网格的位置和大小。</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'zh-tw': '<p>在網格中指定每一個網格的位置和大小。</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'tr': '<p>Grid\'teki bir parçanın konumunu ve grid içerisindeki boyutunu belirler.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'ru': '<p>Определяет позицию и размер grid-элемента внутри grid-сетки.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'pl': '<p>Definiuje pozycję i wielkość elementu grid wewnątrz siatki grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'es': '<p>Define la posición y el tamaño de un elemento en la cuadrícula.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'sv': '<p>Specifierar ett gridelements position och storlek inuti rutnätet.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'fa': '<p>موقعیت و اندازه یک آیتم گرید را در گرید مشخص می کند.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'it': '<p>Specifica la posizione e la dimensione di un elemento nella griglia.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'ko': '<p>그리드 요소의 크기와 위치를 지정합니다.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'el': '<p>Προσδιορίζει την θέση και μέγεθος ενός αντικειμένου του πλέγματος μέσα στο πλέγμα.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'ja': '<p>グリッドアイテムのグリット内の位置とサイズを指定します。</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'ua': '<p>Визначає позицію і розмір grid елемента всередині grid сітки.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'no': '<p>Spesifiserer posisjonen til gridelementet og dets størrelse på rutenettet.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'pt-pt': '<p>Especifica a posição e o tamanho de um elemento na grelha.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'bg': '<p>Определя позицията и размера на grid-елемента в решетката.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'he': '<p>קובע את מקומו ואת גודלו של grid-item בתוך הסריג.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'ca': '<p>Defineix la posició i la mida d\'un element en la quadrícula.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'vi': '<p>Xác định vị trí và kích thước của một đối tượng bên trong grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'ar' : '<p> تحدد الموضع  والحجم لعنصر جريد </p> <p dir="ltr"><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p> ',
    'fi': '<p>Määrittää elementin sijainnin ja koon ruudukossa.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'hu': '<p>Meghatározza egy rácselem pozícióját és méretét.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'id': '<p>Menentukan letak dan ukuran item grid di dalam grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa position ng grid item at and size nito sa loob ng grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'al': '<p>Specifikon pozicionin dhe madhësinë e një grid item brenda në grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
  },
  'grid-column': {
    'en': '<p>Specifies a grid item\'s position within the grid columns.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'lv': '<p>Norāda "grid" elementa/u pozīciju tavā "grid" kolonnā.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'ro': '<p>Specifică poziția unui element al gridului în coloanele gridului.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'fr': '<p>Définit la position d\'un élément de la grille sur les colonnes de la grille.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'zh-cn': '<p>在网格列中指定每一个网格的位置。</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code>',
    'zh-tw': '<p>在網格行中指定每一個網格的位置。</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code>',
    'tr': '<p>Grid\'teki bir parçanın grid kolonundaki pozisyonunu belirler. </p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'de': '<p>Bestimmt die Position eines Elements innerhalb der Spalten des Rasters.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'nl': '<p>Bepaalt de positie van een item binnen de kolommen van het grid.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'pt-br': '<p>Especifica a posição do item de acordo com as colunas da grade.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'ru': '<p>Определяет позицию grid-элемента внутри grid-столбцов.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'pl': '<p>Definiuje pozycję elementu grid w kolumnie grid.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'es': '<p>Define la posición de un elemento respecto a las columnas de la cuadrícula.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'sv': '<p>Specifierar ett gridelements position inuti rutnätets kolumner.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'fa': '<p>موقعیت آیتم گرید در یک ستون گرید را مشخص می کند.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'it': '<p>Specifica la posizione di un elemente rispetto alle colonne della griglia.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'ko': '<p>그리드 요소의 열(column) 위치를 지정합니다.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'el': '<p>Προσδιορίζει την θέση ενός αντικειμένου του πλέγματος μέσα στις στήλες του πλέγματος.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'ja': '<p>グリッドアイテムの列の位置を指定します。</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'ua': '<p>Визначає позицію grid елемента всередині grid стовпців.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'no': '<p>Spesifiserer posisjonen til gridelementet i kolonnene på rutenettet.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'pt-pt': '<p>Especifica a posição de um elemento em respeito às colunas da grelha.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'bg': '<p>Определя позицията на grid-елемента в колоните на решетката.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'he': '<p>קובע את מקומו של הgrid-item בתוך עמודות הסריג.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'ca': '<p>Defineix la posició d\'un element respecte les columnes de la quadrícula.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'vi': '<p>Xác định vị trí của một đối tượng bên trong grid theo cột.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'ar': '<p> تحدد الموضع لعنصر  ضمن اعمدة الجريد </p> <p dir="ltr"> <code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code> </p> ',
    'fi': '<p>Määrittää elementin sijainnin ruudukon pystyriveillä.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'hu': '<p>Meghatározza egy rácselem pozícióját a rács oszlopai közt.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'id': '<p>Menentukan letak item grid di dalam kolom grid.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa position ng grid item sa loob ng mga column ng grid.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'al': '<p>Specifikon pozicionin e një grid item brenda kolonave të gird.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
  },
  'grid-column-end': {
    'en': '<p>Specifies a grid item\'s end position within the grid columns.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'lv': '<p>Norāda "grid" elementa/u beigu pozīciju tavās "grid" kolonnās.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ro': '<p>Specifică poziția de sfârșit a unui element al gridului în coloanele gridului.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'fr': '<p>Définit la position de fin d\'un élément de la grille sur les colonnes de la grille.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'zh-cn': '<p>在网格列中指定每一个网格的最终位置。</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'zh-tw': '<p>在網格行中指定每一個網格的最終位置。</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'tr': '<p>Grid\'teki bir parçanın grid kolonundaki son pozisyonunu belirler.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'de': '<p>Bestimmt die Endposition eines Elements innerhalb der Spalten des Rasters.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'nl': '<p>Bepaalt de eindpositie van een item binnen de gridkolommen.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pt-br': '<p>Especifica a posição final do item de acordo com as colunas da grade.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ru': '<p>Определяет конечную позицию grid-элемента внутри grid-столбцов.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pl': '<p>Definuje pozycję końcową elementu grid w kolumnie grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'es': '<p>Define la posición final de un elemento respecto a las columnas de la cuadrícula.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'sv': '<p>Specifierar ett gridelements slutposition inuti rutnätets kolumner.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'fa': '<p>نقطه پایان آیتم گرید در یک ستون گرید را مشخص می کند.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'it': '<p>Specifica la posizione finale di un elemento rispetto alle colonne della griglia.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ko': '<p>그리드 요소의 마지막 열(column) 위치를 지정합니다.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'el': '<p>Προσδιορίζει την τελική θέση ενός αντικειμένου του πλέγματος μέσα στις στήλες του πλέγματος.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ja': '<p>グリッドアイテムの列の終了位置を指定します。</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ua': '<p>Визначає кінцеву позицію grid елемента всередині grid стовпців.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'no': '<p>Spesifiserer sluttposisjonen til gridelementet i kolonnene på rutenettet.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pt-pt': '<p>Especifica a posição final de um elemento em respeito às colunas da grelha.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'bg': '<p>Определя крайната позиция на grid-елемента в колоните на решетката.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'he': '<p>קובע את מיקומו הסופי של grid-item.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ca': '<p>Defineix la posició final d\'un element respecte les columnes de la quadrícula.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'vi': '<p>Xác định vị trí kết thúc của một đối tượng bên trong grid theo cột.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ar': '<p> تحدد موضع نهاية عنصر ضمن اعمدة لجريد </p> <p dir="ltr"> <code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code> </p>',
    'fi': '<p>Määrittää elementin lopetuskohdan ruudukon pystyriveillä.</p><p><code>&lt;kokonaisluku&gt;</code> <code>span &lt;kokonaisluku&gt;</code></p>',
    'hu': '<p>Meghatározza egy rácselem vég pozícióját a rács oszlopai közt.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'id': '<p>Menentukan letak akhir item grid di dalam kolom grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa end position ng grid item sa loob ng mga column ng grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'al': '<p>Specifikon pozicionin ne fund të një grid item brenda kolonave të grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
  },
  'grid-column-start': {
    'en': '<p>Specifies a grid item\'s start position within the grid columns.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'lv': '<p>Norāda "grid" elementa/u sākuma pozīciju tavās "grid" kolonnās.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ro': '<p>Specifică poziția de început a unui element al gridului în coloanele gridului.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'zh-cn': '<p>在网格列中指定每一个网格的起始位置。</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'zh-tw': '<p>在網格行中指定每一個網格的起始位置。</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'tr': '<p>Grid\'teki bir parçanın grid kolonundaki ilk pozisyonunu belirler.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'fr': '<p>Définit la position du début d\'un élément de la grille sur les colonnes de la grille.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'de': '<p>Bestimmt die Startposition innerhalb der Spalten des Rasters.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'nl': '<p>Bepaalt de startpositie binnen de gridkolommen.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pt-br': '<p>Especifica a posição inicial do item de acordo com as colunas da grade.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ru': '<p>Определяет начальную позицию grid-элемента внутри grid-столбцов.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pl': '<p>Definiuje pozycję początkową elementu grid w kolumnie grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'es': '<p>Define la posición inicial de un elemento respecto a las columnas de la cuadrícula.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'sv': '<p>Specifierar ett gridelements startposition inuti rutnätet.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'fa': '<p>نقطه شروع آیتم گرید در یک ستون گرید را مشخص می کند.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'it': '<p>Specifica la posizione iniziale di un elemento rispetto alle colonne della griglia.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ko': '<p>그리드 요소의 시작 열(column) 위치를 지정합니다.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'el': '<p>Προσδιορίζει την αρχική θέση ενός αντικειμένου του πλέγματος μέσα στις στήλες του πλέγματος.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ja': '<p>グリッドアイテムの列の開始位置を指定します。</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ua': '<p>Визначає початкову позицію grid елемента всередині grid стовпців.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'no': '<p>Spesifiserer startposisjonen til gridelementet på rutenettet.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pt-pt': '<p>Especifica a posição inicial de um elemento em respeito às colunas da grelha.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'bg': '<p>Определя началната позиция на grid-елемента в колоните на решетката.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'he': '<p>קובע את המיקום ההתחלתי של הgrid-item בתוך עמודות הסריג.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ca': '<p>Defineix la posició inicial d\'un element respecte les columnes de la quadrícula.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'vi': '<p>Xác định vị trí bắt đầu của một đối tượng bên trong grid theo cột.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ar': '<p> تحدد موضع بداية عنصر ضمن اعمدة لجريد </p> <p dir="ltr"> <code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code> </p>',
    'fi': '<p>Määrittää elementin aloituskohdan ruudukon pystyriveillä.</p><p><code>&lt;kokonaisluku&gt;</code> <code>span &lt;kokonaisluku&gt;</code></p>',
    'hu': '<p>Meghatározza egy rácselem kezdő pozícióját a rács oszlopai közt.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'id': '<p>Menentukan letak awal item grid di dalam kolom grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa start position ng grid item sa loob ng mga column ng grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'al': '<p>Specifikon pozicionin në fillim të një grid item brenda kolonave te grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
  },
  'grid-row': {
    'en': '<p>Specifies a grid item\'s position within the grid rows.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'lv': '<p>Norāda "grid" elementa/u pozīciju tavās "grid" rindās.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'ro': '<p>Specifică poziția unui element al gridului în rândurile gridului.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'zh-cn': '<p>在网格行中指定每一个网格的位置。</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'zh-tw': '<p>在網格列中指定每一個網格的位置。</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'tr': '<p>Grid\'teki bir parçanın grid satırındaki pozisyonunu belirler.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'fr': '<p>Définit la position d\'un élément de la grille sur les lignes de la grille.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'de': '<p>Bestimmt die Position eines Elements innerhalb der Reihen des Rasters.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'nl': '<p>Bepaalt de positie van een item binnen de gridrijen.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'pt-br': '<p>Especifica a posição do item de acordo com as linhas da grade.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'ru': '<p>Определяет позицию grid-элемента внутри grid-строк.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'pl': '<p>Definiuje pozycję elementu grid w wierszu grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'es': '<p>Define la posición de un elemento respecto a las filas de la cuadrícula.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'sv': '<p>Specifierar ett gridelements position inuti rutnätets rader.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'fa': '<p>موقعیت آیتم گرید در یک سطر گرید را مشخص می کند.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'it': '<p>Specifica la posizione di un elemente rispetto alle righe della griglia.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'ko': '<p>그리드 요소의 행(row) 위치를 지정합니다.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'el': '<p>Προσδιορίζει την θέση ενός αντικειμένου του πλέγματος μέσα στις σειρές του πλέγματος.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'ja': '<p>グリッドアイテムの行の位置を指定します。</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'ua': '<p>Визначає позицію grid елемента всередині grid рядків.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'no': '<p>Spesifiserer posisjonen til gridelementet i radene på rutenettet.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'pt-pt': '<p>Especifica a posição de um elemento em respeito às linhas da grelha.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'bg': '<p>Определя позицията на grid-елемента в редовете на решетката.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'he': '<p>קובע את מקומו של grid-item בתוך שורות הסריג.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'ca': '<p>Defineix la posició d\'un element respecte les files de la quadrícula.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'vi': '<p>Xác định vị trí của một đối tượng bên trong grid theo hàng.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'ar': '<p> تحدد موقع العنصر من خلال صفوف الجريد </p><p dir="ltr"><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'fi': '<p>Määrittää elementin sijainnin ruudukon vaakariveillä.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'hu': '<p>Meghatározza egy rácselem pozícióját a rács sorai közt.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'id': '<p>Menentukan letak item grid di dalam baris grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa position ng grid item sa loob ng mga row ng grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'al': '<p>Specifikon pozicionin brenda rrjeshtave të grid të një grid item.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
   
  },
  'grid-row-end': {
    'en': '<p>Specifies a grid item\'s end position within the grid rows.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'lv': '<p>Norāda "grid elementa/u beigu pozīciju tavās "grid" rindās.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ro': '<p>Specifică poziția de sfârșit a unui element al gridului în rândurile gridului./p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'zh-cn': '<p>在网格行中指定每一个网格的最终位置。</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'zh-tw': '<p>在網格列中指定每一個網格的最終位置。</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'tr': '<p>Grid\'teki bir parçanın grid satırındaki son pozisyonunu belirler.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'fr': '<p>Définit la position de fin d\'un élément de la grille sur les lignes de la grille.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'de': '<p>Bestimmt die Endposition innerhalb der Reihen des Rasters.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'nl': '<p>Bepaalt de eindpositie binnen de gridrijen.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pt-br': '<p>Especifica a posição final do item de acordo com as linhas da grade.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ru': '<p>Определяет конечную позицию grid-элемента внутри grid-строк.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pl': '<p>Definiuje pozycję końcową w wierszu grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'es': '<p>Define la posición final de un elemento respecto a las filas de la cuadrícula.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'sv': '<p>Specifierar ett gridelements slutposition inuti rutnätets rader.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'fa': '<p>نقطه پایان آیتم گرید در یک سطر گرید را مشخص می کند.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'it': '<p>Specifica la posizione finale di un elemento rispetto alle righe della griglia.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ko': '<p>그리드 요소의 마지막 행(row) 위치를 지정합니다.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'el': '<p>Προσδιορίζει την τελική θέση ενός αντικειμένου του πλέγματος μέσα στις σειρές του πλέγματος.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ja': '<p>グリッドアイテムの行の終了位置を指定します。</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ua': '<p>Визначає кінцеву позицію grid елемента всередині grid рядків.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'no': '<p>Spesifiserer sluttposisjonen til gridelementet i radene på rutenettet.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pt-pt': '<p>Especifica a posição final de um elemento em respeito às linhas da grelha.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'bg': '<p>Определя крайната позиция на grid-елемента в редовете на решетката.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'he': '<p>קובע את המיקום הסופי של grid-item בתוך שורות הסריג.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ca': '<p>Defineix la posició final d\'un element respecte les files de la quadrícula.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'vi': '<p>Xác định vị trí kết thúc của một đối tượng bên trong grid theo hàng.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ar': '<p> تحدد موضع نهاية عنصر ضمن صفوف لجريد </p> <p dir="ltr"> <code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code> </p>',
    'fi': '<p>Määrittää elementin lopetuskohdan ruudukon vaakariveillä.</p><p><code>&lt;kokonaisluku&gt;</code> <code>span &lt;kokonaisluku&gt;</code></p>',
    'hu': '<p>Meghatározza egy rácselem vég pozícióját a rács sorai közt.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'id': '<p>Menentukan letak akhir item grid di dalam baris grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa end position ng grid item sa loob ng mga row ng grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'al': '<p>Specifikon pozicionin në fund brenda rrjeshtave të grid të një grid item.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
  },
  'grid-row-start': {
    'en': '<p>Specifies a grid item\'s start position within the grid rows.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'lv': '<p>Norāda "grid" elemanta/u sākuma pozīciju tavās "grid" rindās.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ro': '<p>Specifică poziția de început a unui element al gridului în rândurile gridului.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'zh-cn': '<p>在网格行中指定每一个网格的起始位置。</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'zh-tw': '<p>在網格列中指定每一個網格的起始位置。</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'tr': '<p>Grid\'teki bir parçanın grid satırındaki ilk pozisyonunu belirler.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'fr': '<p>Définit la position du début d\'un élément de la grille sur les lignes de la grille.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'de': '<p>Bestimmt die Startposition innerhalb der Reihen des Rasters.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'nl': '<p>Bepaalt de startpositie binnen de gridrijen.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pt-br': '<p>Especifica a posição inicial do item de acordo com as linhas da grade.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ru': '<p>Определяет начальную позицию grid-элемента внутри grid-строк.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pl': '<p>Definiuje pozycję początkową elementu grid w wierszu grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'es': '<p>Define la posición inicial de un elemento respecto a las filas de la cuadrícula.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'sv': '<p>Specifierar ett gridelements startposition inuti rutnätets rader.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'fa': '<p>نقطه شروع آیتم گرید در یک سطر گرید را مشخص می کند.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'it': '<p>Specifica la posizione iniziale di un elemento rispetto alle righe della griglia.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ko': '<p>그리드 요소의 시작 행(row) 위치를 지정합니다.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'el': '<p>Προσδιορίζει την αρχική θέση ενός αντικειμένου του πλέγματος μέσα στις σειρές του πλέγματος.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ja': '<p>グリッドアイテムの行の開始位置を指定します。</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ua': '<p>Визначає початкову позицію grid елемента всередині grid рядків.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'no': '<p>Spesifiserer startposisjonen til gridelementet i radene på rutenettet.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pt-pt': '<p>Especifica a posição inicial de um elemento em respeito às linhas da grelha.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'bg': '<p>Определя началната позиция на grid-елемента в редовете на решетката.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'he': '<p>קובע את המיקום ההתחלתי של grid-item בתוך שורות הסריג.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ca': '<p>Defineix la posició inicial d\'un element respecte les files de la quadrícula.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'vi': '<p>Xác định vị trí bắt đầu của một đối tượng bên trong grid theo hàng.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ar': '<p> تحدد موضع بداية عنصر ضمن صفوف لجريد </p> <p dir="ltr"> <code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code> </p>',
    'fi': '<p>Määrittää elementin aloituskohdan ruudukon vaakariveillä.</p><p><code>&lt;kokonaisluku&gt;</code> <code>span &lt;kokonaisluku&gt;</code></p>',
    'hu': '<p>Meghatározza egy rácselem kezdő pozícióját a rács sorai közt.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'id': '<p>Menentukan letak awal item grid di dalam baris grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa start position ng grid item sa loob ng mga row ng grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'al': '<p>Specifikon pozicionin fillestar të një gird item brenda rrjeshatve të grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
  },
  'grid-template': {
    'en': '<p>Specifies the sizing and names of the grid\'s rows and columns.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'lv': '<p>Norāda "grid" rindu un kolonnu izmērus un nosaukumus.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'ro': '<p>Specifică mărimea și numele rândurilor și coloanelor gridului.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'fr': '<p>Définit le dimensionnement et les noms des lignes et des colonnes de la grille.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'zh-cn': '<p>指定网格的行和列的大小以及名称。</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'zh-tw': '<p>指定網格的列和行的大小以及名稱。</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'tr': '<p>Grid\'in satır ve kolonlarının isimlerini ve ölçülerini belirler.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'de': '<p>Bestimmt die Abmessungen und Namen der Reihen und Spalten des Rasters.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'nl': '<p>Bepaalt de afmetingen en namen van de gridrijen en -kolommen.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'pt-br': '<p>Especifica o tamanho das linhas e colunas da grade.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'ru': '<p>Определяет размер и названия для grid-строк и столбцов.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'pl': '<p>Definiuje wielkość i nazwy wierszy i kolumn grid.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'es': '<p>Define el tamaño y nombres de las filas y las columnas de la cuadrícula.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'sv': '<p>Specifierar storlek och namn för rutnätets rader och kolumner.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'fa': '<p>اندازه و نام سطرها و ستون های گرید را مشخص می کند.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'it': '<p>Specifica la dimensione e i nomi delle righe e delle colonne della griglia.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'ko': '<p>그리드의 행(row)과 열(column)에 대한 크기와 명칭을 지정합니다.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'el': '<p>Προσδιορίζει το μέγεθος και τα ονόματα των σειρών και στηλών του πλέγματος.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'ja': '<p>グリッドの行と列のサイズと名前を指定します。</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'ua': '<p>Визначає розмір і назви для grid рядків і стовпців.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'no': '<p>Spesifiserer størrelsene og navnene på radene og kolonnene til rutenettet.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'pt-pt': '<p>Especifica as dimensões e nomes das linhas e colunas da grelha.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'bg': '<p>Определя размера и имената на редовете и колоните на решетката.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'he': '<p>קובע את הגודל והשמות של השורות והעמודות של הסריג.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'ca': '<p>Defineix la mida i noms de les files i les columnes de la quadrícula.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'vi': '<p>Xác định kích thước và tên các cột, hàng bên trong grid.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'ar': '<p> تحدد احجام واسامي صفوف اعمدة الجريد</p><p dir="ltr"><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'fi': '<p>Määrittää ruudukon vaaka- ja pystyrivien koot ja nimet.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'hu': '<p>Meghatározza a rács oszlopainak és sorainak méretét és elnevezésüket.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'id': '<p>Menentukan ukuran dan nama dari baris dan kolom grid.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa sukat at pangalan ng rows at columns ng grid.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'al': '<p>Specifikon madhësitë dhe emrat e rrjeshtave dhe kolonave të grid.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
  },
  'grid-template-areas': {
    'en': '<p>Specifies named grid areas.</p><p><code>&lt;grid-name&gt;</code></p>',
    'lv': '<p>Norāda "grid" zonu nosaukumus.</p><p><code>&lt;grid-name&gt;</code></p>',
    'ro': '<p>Specifică zonele numite ale gridului.</p><p><code>&lt;grid-name&gt;</code></p>',
    'zh-cn': '<p>指定被命名的网格区域。</p><p><code>&lt;grid-name&gt;</code></p>',
    'zh-tw': '<p>指定被命名的網格區域。</p><p><code>&lt;grid-name&gt;</code></p>',
    'tr': '<p>İsimlendirilmiş grid alanlarını belirler.</p><p><code>&lt;grid-name&gt;</code></p>',
    'fr': '<p>Définit les régions de grille nommées</p><p><code>&lt;grid-name&gt;</code></p>',
    'de': '<p>Bestimmt benannte Rasterbereiche.</p><p><code>&lt;grid-name&gt;</code></p>',
    'nl': '<p>Bepaalt de benoemde gridgebieden.</p><p><code>&lt;grid-name&gt;</code></p>',
    'pt-br': '<p>Especifica as áreas da grade.</p><p><code>&lt;grid-name&gt;</code></p>',
    'ru': '<p>Определяет названные grid-зоны.</p><p><code>&lt;grid-name&gt;</code></p>',
    'pl': '<p>Definiuje nazwy powierzchni grid.</p><p><code>&lt;grid-name&gt;</code></p>',
    'es': '<p>Define las áreas de la cuadrícula nombradas.</p><p><code>&lt;grid-name&gt;</code></p>',
    'sv': '<p>Specifierar namngivna grid områden.</p><p><code>&lt;grid-name&gt;</code></p>',
    'fa': '<p>ناحیه های گرید را مشخص می کند.</p><p><code>&lt;grid-name&gt;</code></p>',
    'it': '<p>Specifica le aree denominate della griglia.</p><p><code>&lt;grid-name&gt;</code></p>',
    'ko': '<p>명시된 그리드의 영역을 지정합니다.</p><p><code>&lt;grid-name&gt;</code></p>',
    'el': '<p>Προσδιορίζει κατονομασμένες περιοχές του πλέγματος.</p><p><code>&lt;grid-name&gt;</code></p>',
    'ja': '<p>グリッドの領域を指定します。</p><p><code>&lt;grid-name&gt;</code></p>',
    'ua': '<p>Визначає названі grid зони.</p><p><code>&lt;grid-name&gt;</code></p>',
    'no': '<p>Spesifiserer navngitte områder på rutenettet.</p><p><code>&lt;grid-name&gt;</code></p>',
    'pt-pt': '<p>Especifica as áreas nomeadas da grelha.</p><p><code>&lt;grid-name&gt;</code></p>',
    'bg': '<p>Определя наименованите зони от решетката.</p><p><code>&lt;grid-name&gt;</code></p>',
    'he': '<p>קובע את אזורי הסריג שנקבעו.</p><p><code>&lt;grid-name&gt;</code></p>',
    'ca': '<p>Defineix les àrees de la quadrícula anomenades.</p><p><code>&lt;grid-name&gt;</code></p>',
    'vi': '<p>Xác định vùng grid được đặt tên.</p><p><code>&lt;grid-name&gt;</code></p>',
    'ar': '<p>تحدد عناصر الجريد المسماة</p><p dir="ltr"><code>&lt;grid-name&gt;</code></p>',
    'fi': '<p>Määrittää nimetyt ruudukkoalueet.</p><p><code>&lt;ruudukon-nimi&gt;</code></p>',
    'hu': '<p>Meghatározza egy elnevezett rács területet.</p><p><code>&lt;grid-name&gt;</code></p>',
    'id': '<p>Menentukan area dari grid yang telah diberi nama.</p><p><code>&lt;grid-name&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa mga nilagyan ng name na grid area.</p><p><code>&lt;grid-name&gt;</code></p>',
    'al': '<p>Specifikon zonat e emëruara të grid.</p><p><code>&lt;grid-name&gt;</code></p>',
  },
  'grid-template-columns': {
    'en': '<p>Specifies the sizing and names of the grid\'s columns.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'lv': '<p>Norāda "grid" kolonnu nosaukumus un izmērus.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ro': '<p>Specifică mărimea și numele coloanelor gridului.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'fr': '<p>Définit le dimensionnement et les noms des colonnes de la grille.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'zh-cn': '<p>指定网格中列的大小和名称。</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'zh-tw': '<p>指定網格中行的大小和名稱。</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'tr': '<p>Grid kolonlarının isimlerini ve ölçülerini belirler.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'de': '<p>Bestimmt die Abmessungen und Namen der Spalten des Rasters.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'nl': '<p>Bepaalt de afmetingen en namen van de gridkolommen.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'pt-br': '<p>Especifica o tamanho das colunas da grade.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ru': '<p>Определяет размер и названия для grid-столбцов.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'pl': '<p>Definiuje wielkość i nazwy kolumn grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'es': '<p>Especifica el tamaño y los nombres de las columnas de la cuadrícula.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'sv': '<p>Specifierar storlek och namn för rutnätets kolumner.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'fa': '<p>اندازه و نام ستون های گرید را مشخص می کند.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'it': '<p>Specifica la dimensione e i nomi delle colonne della griglia.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ko': '<p>그리드의 열(column) 크기와 명칭을 지정합니다.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'el': '<p>Προσδιορίζει το μέγεθος και τα ονόματα των στηλών του πλέγματος.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ja': '<p>グリッドの列のサイズと名前を指定します。</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ua': '<p>Визначає розмір і назви для grid стовпців.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'no': '<p>Spesifiserer størrelsene og navnene på kolonnene til rutenettet.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'pt-pt': '<p>Especifica as dimensões e nomes das colunas da grelha.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'bg': '<p>Определя размера и имената на колоните на решетката.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'he': '<p>קובע את הגדלים ואת השמות של עמודות הסריג.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ca': '<p>Especifica la mida i els noms de les columnes de la quadrícula.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'vi': '<p>Xác định kích thước và tên các cột bên trong grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ar': '<p>تحدد المقاسات والاسامي لاعمدة الشبكة </p><p dir="ltr"><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'fi': '<p>Määrittää ruudukon pystyrivien koot ja nimet.</p><p><code>&lt;pituusyksikkö&gt;</code> <code>&lt;prosenttiarvo&gt;</code> <code>&lt;fr-yksikkö&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'hu': '<p>Meghatározza a rács oszlopainak méretét és nevét.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'id': '<p>Menentukan ukuran dan nama kolom dari grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'tl': '<p>Tumutukoy ito sa sukat at pangalan ng columns ng grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'al': '<p>Specifikon madhesitë dhe emrat e kolonave të grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
  },
  'grid-template-rows': {
    'en': '<p>Specifies the sizing and names of the grid\'s rows.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'lv': '<p>Norāda "grid" rindu nosaukumus un izmērus.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ro': '<p>Specifică mărimea și numele rândurilor gridului.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'zh-cn': '<p>指定网格中行的大小和名称。</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'zh-tw': '<p>指定網格中列的大小和名稱。</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'tr': '<p>Grid satırlarının isimlerini ve ölçülerini belirler.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'fr': '<p>Définit le dimensionnement et les noms des lignes de la grille.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'de': '<p>Bestimmt die Abmessungen und Namen der Reihen des Rasters.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'nl': '<p>Bepaalt de afmetingen en namen van de gridrijen.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'pt-br': '<p>Especifica o tamanho das linhas da grade.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ru': '<p>Определяет размер и названия для grid-строк.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'pl': '<p>Definiuje wielkość i nazwy wierszy grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'es': '<p>Define el tamaño y los nombres de las filas de la cuadrícula.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'sv': '<p>Specifierar storlek och namn för rutnätets rader.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'fa': '<p>اندازه و نام سطرهای گرید را مشخص می کند.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'it': '<p>Specifica la dimensione e i nomi delle righe della griglia.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ko': '<p>그리드의 행(row) 크기와 명칭을 지정합니다.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'el': '<p>Προσδιορίζει το μέγεθος και τα ονόματα των σειρών του πλέγματος.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ja': '<p>グリッドの行のサイズと名前を指定します。</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ua': '<p>Визначає розмір і назви для grid рядків.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'no': '<p>Spesifiserer størrelsene og navnene på radene til rutenettet.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'pt-pt': '<p>Especifica as dimensões e nomes das linhas da grelha.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'bg': '<p>Определя размера и имената на редовете на решетката.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'he': '<p>קובע את הגדלים והשמות של שורות הסריג.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ca': '<p>Defineix la mida i elsnnom de les files de la quadrícula.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'vi': '<p>Xác định kích thước và tên các hàng bên trong grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ar': '<p>تحدد المقاسات والاسامي لصفوف الشبكة </p><p dir="ltr"><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'fi': '<p>Määrittää ruudukon vaakarivien koon ja nimet.</p><p><code>&lt;pituusyksikkö&gt;</code> <code>&lt;prosenttiarvo&gt;</code> <code>&lt;fr-yksikkö&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'hu': '<p>Meghatározza a rács sorainak méretét és nevét.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'id': '<p>Menentukan ukuran dan nama baris dari grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'tl': '<p>Tumutukoy ito sa sukat at pangalan ng rows ng grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'al': '<p>Specifikon madhesitë dhe emrat e rrjeshtave të grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
  },
  'order': {
    'en': '<p>Specifies the order of the grid item.</p><p><code>&lt;integer&gt;</code></p>',
    'lv': '<p>Norāda "grid" elementu secību.</p><p><code>&lt;integer&gt;</code></p>',
    'ro': '<p>Specifică ordinea elementului în grid.</p><p><code>&lt;integer&gt;</code></p>',
    'zh-cn': '<p>指定每一个网格的顺序。</p><p><code>&lt;integer&gt;</code></p>',
    'zh-tw': '<p>指定每一個網格的順序。</p><p><code>&lt;integer&gt;</code></p>',
    'tr': '<p>Grid\'teki bir parçanın sırasını belirler.</p><p><code>&lt;integer&gt;</code></p>',
    'fr': '<p>Définit l\'ordre de l\'élément dans la grille.</p><p><code>&lt;integer&gt;</code></p>',
    'de': '<p>Bestimmt die Reihenfolge der Rasterelemente.</p><p><code>&lt;integer&gt;</code></p>',
    'nl': '<p>Bepaalt de volgorde van het griditem.</p><p><code>&lt;integer&gt;</code></p>',
    'pt-br': '<p>Especifica a ordem do item na grade.</p><p><code>&lt;integer&gt;</code></p>',
    'ru': '<p>Определяет порядок grid-элемента.</p><p><code>&lt;integer&gt;</code></p>',
    'pl': '<p>Definiuje kolejność elementu grid.</p><p><code>&lt;integer&gt;</code></p>',
    'es': '<p>Define el orden del elemento de la cuadrícula.</p><p><code>&lt;integer&gt;</code></p>',
    'sv': '<p>Specifierar ett grid elements sorteringsorder.</p><p><code>&lt;integer&gt;</code></p>',
    'fa': '<p>ترتیب آیتم های گرید را مشخص می کند.</p><p><code>&lt;integer&gt;</code></p>',
    'it': '<p>Specifica l\'ordine degli elementi della griglia.</p><p><code>&lt;integer&gt;</code></p>',
    'ko': '<p>그리드 요소의 순서를 지정합니다.</p><p><code>&lt;integer&gt;</code></p>',
    'el': '<p>Προσδιορίζει την σειρά του αντικειμένου στο πλέγμα.</p><p><code>&lt;integer&gt;</code></p>',
    'ja': '<p>グリッドアイテムの順序を指定します。</p><p><code>&lt;integer&gt;</code></p>',
    'ua': '<p>Визначає порядок grid елемента.</p><p><code>&lt;integer&gt;</code></p>',
    'no': '<p>Spesifiserer rekkefølgen til gridelementet.</p><p><code>&lt;integer&gt;</code></p>',
    'pt-pt': '<p>Especifica a ordem do elemento da grelha.</p><p><code>&lt;integer&gt;</code></p>',
    'bg': '<p>Определя подредбата на grid-елемента.</p><p><code>&lt;integer&gt;</code></p>',
    'he': '<p>קובע את הסדר של הgrid-item.</p><p><code>&lt;integer&gt;</code></p>',
    'ca': '<p>Defineix l\'ordre de l\'element de la quadrícula.</p><p><code>&lt;integer&gt;</code></p>',
    'vi': '<p>Xác định thứ tự của đối tượng bên trong grid.</p><p><code>&lt;integer&gt;</code></p>',
    'ar': '<p>تحدد ترتيب العنصر في الجريد.</p><p dir="ltr"><code>&lt;integer&gt;</code></p>',
    'fi': '<p>Määrittää ruudukkoelementin järjestyksen.</p><p><code>&lt;kokonaisluku&gt;</code></p>',
    'hu': '<p>Meghatározza a rácselem sorrendjét.</p><p><code>&lt;integer&gt;</code></p>',
    'id': '<p>Menentukan urutan dari item grid.</p><p><code>&lt;integer&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa order ng grid item.</p><p><code>&lt;integer&gt;</code></p>',
    'al': '<p>Specifikon rregullin e një grid item.</p><p><code>&lt;integer&gt;</code></p>',
  },
};
